/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;

/**
 *
 * @author amlopes1
 */
public class Frases extends javax.swing.JFrame {

    /**
     * Creates new form Frases
     */
    public Frases() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFrase = new javax.swing.JLabel();
        BtnNegativo = new javax.swing.JButton();
        BtnVerdade = new javax.swing.JButton();
        BtnPositivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnNegativo.setText("Msg Negativa");
        BtnNegativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNegativoActionPerformed(evt);
            }
        });

        BtnVerdade.setText("Msg Verdadeira");
        BtnVerdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerdadeActionPerformed(evt);
            }
        });

        BtnPositivo.setText("Msg Positiva");
        BtnPositivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPositivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(BtnPositivo)
                        .addGap(18, 18, 18)
                        .addComponent(BtnNegativo)
                        .addGap(18, 18, 18)
                        .addComponent(BtnVerdade))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(lblFrase)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblFrase)
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnNegativo)
                    .addComponent(BtnVerdade)
                    .addComponent(BtnPositivo))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPositivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPositivoActionPerformed
        lblFrase.setText("Nunca é tarde demais");
    }//GEN-LAST:event_BtnPositivoActionPerformed

    private void BtnNegativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNegativoActionPerformed
        lblFrase.setText("Só dará errado se você tentar");
    }//GEN-LAST:event_BtnNegativoActionPerformed

    private void BtnVerdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerdadeActionPerformed
        lblFrase.setText("O professor Yoshi é parecido com o ex-jogador Caio Ribeiro");
    }//GEN-LAST:event_BtnVerdadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frases().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnNegativo;
    private javax.swing.JButton BtnPositivo;
    private javax.swing.JButton BtnVerdade;
    private javax.swing.JLabel lblFrase;
    // End of variables declaration//GEN-END:variables
}
